version: "2.29.1"
name: cold-user

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
